### ISSUE TITLE
Not recalling values correctly?

### ISSUE THREAD

**Issue by Skeen** [kadtools/kad-webrtc#10]
Hi,

I was playing around with the library, and I stumpled upon a piece of unexpected behavior. 
Namely nodes recalling different values for the same key.

The behavior can be produced by the following sequence:

* Two nodes (1 and 2) join a network.
* Node 1 puts the value `boop` under the key `beep`.
* Node 2 puts the value `mew` under the key `beep`.
* Node 1 gets the value for `beep`; `mew`.
* Node 2 gets the value for `beep`; `boop`.

I would have expected both nodes to get `mew` when querying for `beep`.

I have tried the same thing with three nodes, and only the node overriding the value gets the old one back. The other two nodes get the new value.

The sequence (2 nodes) as a modified version of the `webrtc-browser` example;
```js
'use strict';

var kademlia = require('kad');
var EventEmitter = require('events').EventEmitter;
var WebRTC = require('../..');

// The two nodes share a signaller
var signaller = new EventEmitter();

// Create our first node
var node1 = new kademlia.Node({
  transport: new WebRTC(new WebRTC.Contact({
    nick: 'node1'
  }), { signaller: signaller }),
  storage: new kademlia.storage.LocalStorage('node1')
});

// Create a second node
var node2 = new kademlia.Node({
  transport: new WebRTC(new WebRTC.Contact({
    nick: 'node2'
  }), { signaller: signaller }),
  storage: new kademlia.storage.LocalStorage('node2')
});

node2.on('connect', onConnect);

node2.connect({ nick: 'node1' });

function onConnect() {
  node1.put('beep', 'boop', onPut);
}

function onPut(err) {
  node2.put('beep', 'mew', onPut2);
}

function onPut2(err) {
  node1.get('beep', function(err, value) { onGet('node1', err, value) });
  node2.get('beep', function(err, value) { onGet('node2', err, value) });
}

function onGet(nodeID, err, value) {
  alert(nodeID + ':' + value); // 'boop'
}
```

**Comment by Skeen** [comment]
Note: There's no problem if a node overrides it's own value (i.e. if it haven't been overriden by another node), i.e.:

* Node 1 puts the value `boop` under the key `beep`.
* Node 1 puts the value `mew` under the key `beep`.
* Node 1 gets the value for `beep`; `mew`.
* Node 2 gets the value for `beep`; `mew`.

But: 

* Node 1 puts the value `boop` under the key `beep`.
* Node 2 puts the value `mew` under the key `beep`.
* Node 1 puts the value `mew2` under the key `beep`.
* Node 1 gets the value for `beep`; `mew`.
* Node 2 gets the value for `beep`; `mew2`.

**Comment by gordonwritescode** [comment]
This is inherent in the design of a DHT. Without a validation system that enforces immutable pairs (like content-addressing) there is no guarantee that all nodes will have the same value for a given key due to time between replication and republishing, and local copies vs remote copies, etc.

**Comment by gordonwritescode** [comment]
You can implement a validation method described above using the `validator` options in the `Node` constructor: http://kadtools.github.io/Node.html#-inner-validator__anchor

**Comment by Skeen** [comment]
I guess I was just expecting 'instant' replication to the k-nearest neighbors, i.e. pushing updates to the replicatees.

**Comment by Skeen** [comment]
Don't get me wrong; I'm not saying my expectation is right, rather the opposite; I think you're right, it makes sense with the delayed replication, and the eventual consistency.

I'll look into making a validator :), thanks for the link.

**Comment by gordonwritescode** [comment]
If less than `ALPHA` (3) contacts are returned from the `FIND_NODE` RPC, then the node will store a copy locally: https://github.com/kadtools/kad/blob/master/lib/node.js#L256

In your case, there are only two nodes, so each of them store their own local copy and hence when the other asks for the value they get the one the other published.

**Comment by Skeen** [comment]
I see. I'll play around with larger swarms then :)

Is there any way to handle churn / leaving?
- It seems disconnect is undefined on the nodes I'm getting in the examples.

**Comment by omphalos** [comment]
@Skeen sorry I don't know what you mean here:

> It seems disconnect is undefined on the nodes I'm getting in the examples.

What exactly is undefined?

**Comment by omphalos** [comment]
> Is there any way to handle churn / leaving?

Copies are stored in nearest nodes, but if all those nodes leave (there's too much churn) the value will get lost.  (@gordonwritescode please correct me if I'm wrong about this.)

@Skeen are you asking for something that would replicate on disconnect?

**Comment by Skeen** [comment]
@omphalos if I modify the `webrtc-browser` example's `onGet` callback to be;
```js
function onGet(err, value) {
  alert(value); // 'boop'
  node2.disconnect();
}
```
Then I'd expect node2 to disconnect from the network, after alerting the value of 'beep', but instead I get; 
```
Uncaught TypeError: node2.disconnect is not a function
```

**Comment by Skeen** [comment]
@omphalos I see now that churn is actually working; my issue, it seems,  was using n < `ALPHA`.

With n=8, the network seems to handle churn just fine, and the network keeps working unless I crash al replicates, at which point I lose data (which is completely expected).

When enough nodes crash, the warning about RPC failure becomes an alert, which seems reasonable, indicating a complete failure of the network.

**Comment by omphalos** [comment]
> Then I'd expect node2 to disconnect from the network, after alerting the value of 'beep', but instead I get;

    Uncaught TypeError: node2.disconnect is not a function

Ah, I see.  The `kad` dependency was not up to date.  I just updated package.json (and verified everything still works).  You should be able to use `disconnect` now.

**Comment by Skeen** [comment]
@omphalos AWESOME! - I was a bit puzzled, as it was in the documentation, but indeed not on the object itself, didn't consider the versioning. - Thanks.

**Comment by omphalos** [comment]
@Skeen cool, do you think it's okay to close this issue now is there something remaining that I missed?

**Comment by Skeen** [comment]
Oh, I meant to close it with my previous comment, my apologies.
