### ISSUE TITLE
Node calling put() not updating local database? 

### ISSUE THREAD

**Issue by zanetu** [kadtools/kad-webrtc#8]
This might be a [kad](https://github.com/kadtools/kad) bug, but I'm reporting here anyway as I used a variation of [webrtc-browser-e2e](https://github.com/kadtools/kad-webrtc/tree/35f624aedb4769b95042a1237c25a4659e9ccec4/examples/webrtc-browser-e2e). 

See inline comment below. 

```
'use strict';  // the first line taken from webrtc-browser-e2e source code

var kademlia = require('kad');
var WebRTC = require('../..');
var webSocket = require('./web-socket');
var SignalClient = require('./signal-client');
var EventEmitter = require('events').EventEmitter;
var signalClient1 = new SignalClient('node1');
var signalClient2 = new SignalClient('node2');

webSocket.on('open', function() {

  // Create our first node
  var node1 = new kademlia.Node({
    transport: new WebRTC(new WebRTC.Contact({
      nick: 'node1'
    }), { signaller: signalClient1 }),
    storage: new kademlia.storage.LocalStorage('node1')
  });

  // Create a second node
  var node2 = new kademlia.Node({
    transport: new WebRTC(new WebRTC.Contact({
      nick: 'node2'
    }), { signaller: signalClient2 }),
    storage: new kademlia.storage.LocalStorage('node2')
  });

  node2.on('connect', onConnect);

  node2.connect({ nick: 'node1' });  // the last line taken from webrtc-browser-e2e source code
// different code below
  function onConnect() {
    node1.put('key', '1', onPut1);
  }

  function onPut1(err) {
    node2.put('key', '2', onPut2);
  }

  function onPut2(err) {
    node2.get('key', onGet2);
  }

  function onGet2(err, value) {
    alert(value); // expected: '2'; actual: '1'
	node1.get('key', onGet1);
  }
  
  function onGet1(err, value) {
    alert(value); // expected: '2'; actual: '2'
  }

});
```

**Comment by gordonwritescode** [comment]
Wait for it... "it's a feature, not a bug" :wink: 

The reason for this is that the `Node#put` method is a wrapper for the [Kademlia](http://www.scs.stanford.edu/~dm/home/papers/kpos.pdf) protocol's `STORE` RPC method sent to the network. Here's what's going on:

1. `Node` wishes to *put* an item into the DHT
2. `Router` returns `ALPHA` (3) contacts closest to the key
3. `RPC` (transport adapter) issues a STORE `Message` to the returned contacts

[Here is the code for the above flow](http://kadtools.github.io/lib_node.js.html#line110).

The point is that, in a Kademlia DHT, data is stored with nodes whose `nodeID` is closest to the item's `key` (using the XOR metric), therefore if you are meant to store the value you will eventually have it republished back to you by another node during that node's regular [replication](http://kadtools.github.io/lib_node.js.html#line220).

If you need to store an item locally, I suggest using the storage adapter directly:

```js
var store = new kad.storage.LocalStorage('prefix');
var contact = new WebRTC.Contact({ nick: 'node' });
var transport = new WebRTC(contact, { signaller: { /* signal client */ } })
var node = new kad.Node({ transport: transport, storage: store });

// store locally...
store.put('beep', 'boop', callback);
// store remotely...
node.put('beep', 'boop', callback);
```

> Be careful to remember to manually call your validator if you are using one, since the storage adapter is not aware of it.

Hope this helps!

**Comment by omphalos** [comment]
@gordonwritescode Thanks for taking the time to answer this.  In this case shouldn't node2's `put` cause the 3 nearest contacts (including both node1 and node2) to store the updated value?

**Comment by gordonwritescode** [comment]
Hmm, I think you are right @omphalos, STORE is done after an initial FIND_NODE and so one would think that if there are only two nodes, that the receiving node would respond back with the contact for the sender.

However, the implementation we have deliberately excludes the sender from the results. The paper doesn't seem to make this restriction though, it simply says that the recipient of a FIND_NODE request must respond with `k` contacts close to key or if less than `k` in all buckets, all known contacts. 

But to be clear, the local storage of data on `put()` would be a side effect of having less than `k` total nodes, not an always expected behavior?

**Comment by zanetu** [comment]
@gordonwritescode 

Speaking of exclusion of sender, I am also a bit puzzled why you have to do that in your implementation. I haven't gone through all your code but it seems to me that you don't consider a single node to be a valid KAD network and forbid storing data on the publishing node itself. (Correct me if I were wrong. ) From my point of view, kadtools/kad#47 is more or less correlated with this notion. If an isolated node were deemed a legitimate KAD network, you would not need to deal with connectivity issues like [this](https://github.com/kadtools/kad/blob/0e21260f575f5788f58f6c40427151fefb4d85fd/lib/router.js#L46) any more, as a node is always connected, at least to itself. Similarly, I would be less worried about maintaining states like `isOnline`, as `node.get` and `node.put` would always succeed. So, is there any severe consequence when an isolated node is deemed a legitimate KAD network? If not, I'd suggest removing restrictions (at least as an option) such as exclusion of the sender, as they may cause quite a few problems at early stages of a KAD network, where nodes tend to be sparse. 

> But to be clear, the local storage of data on put() would be a side effect of having less than k total nodes, not an always expected behavior?

As an aside, it is worth noting that local storage has precedence over RPC in [`node.get`](https://github.com/kadtools/kad/blob/0e21260f575f5788f58f6c40427151fefb4d85fd/lib/node.js#L169), which looks weird to me. To my mind, `node.get` should, by default, be a remote query to Kademlia DHT. Locally cached value can be a fallback but should not be given precedence. `node.get` should try to get the most up-to-date data in the first place. After all, the probability of update-to-date data being stored locally is very low when the KAD network has plenty of nodes. Code-wise, I'd prefer something like the following. 
```
Node.prototype.get = function(key, callback, options) {
	var self = this;
	this._log.debug('attempting to get value for key %s', key);
	if(options && options['prefersLocal']) {
		this._storage.get(key, function(err, item) {
			if (!err && item) {
				return callback(null, JSON.parse(item).value);
			}
			getRemote();
		});
	}
	else {
		getRemote();
	}
	function getRemote() {
		self._router.findValue(key, function(err, value) {
			if (err) {
				return callback(err);
			}
			callback(null, value);
		});
	}
};
```

**Comment by zanetu** [comment]
[**@gordonwritescode**](https://github.com/gordonwritescode) commented on [Feb 14, 2016, 6:39 PM EST](https://github.com/kadtools/kad-webrtc/issues/8#issuecomment-184006789 "2016-02-14T23:39:28Z - Replied by Github Comment Enhancer"):
> therefore if you are meant to store the value you will eventually have it republished back to you by another node during that node's regular [replication](http://kadtools.github.io/lib_node.js.html#line220).

I waited for 1 min (by changing `node2.get('key', onGet2);` to `setTimeout(function() { node2.get('key', onGet2); }, 60000);`) but replication did not take place. I don't want to wait that long when running my code. 
> If you need to store an item locally, I suggest using the storage adapter directly:

Maintaining separate local storage can be cumbersome and I'd rather avoid that overhead altogether.

**Comment by gordonwritescode** [comment]
I'll try to answer to some of the above:

* We exclude the calling node from results to prevent nodes from ending up in their own routing table. This is undesirable as RPC calls should not be made to one's self.
* A single node is not a valid network of any kind, which is why you must be aware of at least 1 peer to be "online".
* I agree that `Node#get` should not check local storage first, but should fallback to it - I'll make that change. Similarly, I would be happy to add the same fallback for `Node#put`, which should effectively resolve your "one node network" problem. The `Node#put` local fallback will only be used if less than `ALPHA` nodes are available to accept a `STORE`.

I think this should effectively resolve *this* issue for you. It would allow you to use `Node#get` and `Node#put` without having any peers, but would solve it in such a way that nodes do not end up in their own routing table.

**Comment by gordonwritescode** [comment]
Okay, I have pushed https://github.com/kadtools/kad/commit/c58c1ab7e3029d5fe72f3e3ec6ce1644b741d8fe which resolves this issue. Now `Node#get` and `Node#put` will prefer remote over local, unless remote fails or returns fewer than `ALPHA` contacts, in which case, the data will be loaded from or stored in the local storage adapter.

This will be published later this week at `v1.4.0` along with the updates for https://github.com/kadtools/kad/issues/47 once they are ready.

**Comment by zanetu** [comment]
@gordonwritescode 

I have some doubt over [this line](https://github.com/kadtools/kad/blob/master/lib/node.js#L154). (Since I'm not familiar with all the code, you can ignore my feedback if you don't consider it an issue. ) In my opinion, it should be something like: 
```
// node._storage.put may be called even if error occurs in the following async.each
contacts.length < constants.ALPHA && node._storage.put(key, JSON.stringify(item));
async.each(contacts, function(contact, done) {
	var message = new Message({
		method: 'STORE',
		params: { item: item, contact: node._self }
	});
	node._log.debug('sending STORE message to %j', contact);
	node._rpc.send(contact, message, done);
}, function(err) {
	if (err) {
		return callback(err);
	}
	callback();
});
```

**Comment by gordonwritescode** [comment]
@zanetu ah, thanks. That's correct, if the RPC instance spits a *fatal* error (not a timeout or RPC error response), we won't use the local storage. 

Will fix.

**Comment by gordonwritescode** [comment]
However, if the RPC does fail hard like that, we probably want to know about it and not suppress it. Let me think about it.
